node {

    stage('CloneRepo') {
         git branch: 'main', 
         url: 'https://github.com/Jewel73/naztech-jdbc.git'
    }
    
    stage('Build') {
        sh './gradlew clean'
        sh './gradlew build'
    }

}
