pipeline {
    agent any

    stages {
        stage('CloneRepo') {
            steps {
                git branch: 'main', 
                url: 'https://github.com/Jewel73/naztech-jdbc.git'
            }
        }
        
        stage('Build') {
            steps {
                sh './gradlew clean'
                sh './gradlew build'
            }
        }
    }
}
